#!/bin/bash

if [ $# = 0 ]; then
    echo "Usage: Set time on remote machine
Examples -
$ $(basename $0) root@host1 root@host2
$ $(basename $0) '-J hostA,hostB root@host1' '-J hostA,hostB root@host2'"    
    exit 1
fi

NOW=$(date +"%Y-%m-%d %T")
echo "Now: $NOW"

sync() {
    for HOST in $1 $2 $3 $4 $5 $6 $7 $8 $9; do
        echo "HOST: $HOST"
        ssh -T $HOST << EOSSH
timedatectl set-timezone Asia/Shanghai
date --set "$NOW"
timedatectl --adjust-system-clock
hwclock --systohc --utc
echo "DATE: $(date) [$(hostname)]"
EOSSH
    done
}

check() {
    for HOST in $1 $2 $3 $4 $5 $6 $7 $8 $9; do
        echo "HOST: $HOST"
        ssh -T $HOST << EOSSH
echo "DATE: $(date) [$(hostname)]"
echo "DATE: \$(date) [\$(hostname)]"
EOSSH
    done
}

sync $*
check $*

echo "ssh time sync done"
